### ISSUE TITLE
[HU] Incluir en el README los componentes del equipo

### ISSUE THREAD

**Issue by JJ** [testing-kakapos/curso-QA#1]
## Descripción de alto nivel

Nombre y nick, por lo menos...

## Dado/Y/Entonces/Cuando

Describir las diferentes posibilidades en diferentes escenarios.

**Comment by rafasanjuan** [comment]
Añadido en el commit 339649530ef70fc8ad6276b3ddbb76c8dc81f8ed

**Comment by JJ** [comment]
Recuerda que puedes cerrar un issue directamente desde un commit con "closes #xx"
