### ISSUE TITLE
Discusión sobre las herramientas del proyecto

### ISSUE THREAD

**Issue by rafasanjuan** [testing-kakapos/curso-QA#6]
En este issue se discutirán las herramientas ha usar en el proyecto.

Personalmente ya que queremos hacer un dashboard de visualicación de incidencias de trafico podemos usar plotly/dash. Es un framework sobre Python para crear webapps facilmente, da visualicaciónes interactivas y creo que puede cumplir nuestras necesidades de mostrar un mapa y alguna información extra.

**Comment by iambouali** [comment]
Me parece bien. ¿Usamos Django & Javascript para crear la web donde se serviran los datos?

**Comment by iambouali** [comment]
Posibles teconologías que podemos usar:

* Django
* Javascript 
* HTML5 / CSS (SCSS)
* Plotly

**Comment by ghost** [comment]
Me parece bien. ¿Usamos Django & Javascript para crear la web donde se serviran los datos?

Posibles teconologías que podemos usar:

* Django
* Javascript
* HTML5 / CSS (SCSS)
* Plotly

**Comment by Guillergood** [comment]
También se podría usar Laravel o si lo veis complicado Twig. Kotlin también es una opción junto con html/css/JavaScript

**Comment by rafasanjuan** [comment]
Vale me explico un poco mejor.

Plotly es una librería para crear gráficos interactivos que tiene soporte para Javascript y Python entre otros, la empresa del mismo nombre también desarrolla un framework de desarrollo web llamado Dash que es simplemente una capa sobre el framework Flask.

Dash está pensado para crear dashboards de visualización (sitios web) de forma fácil y creo que nos da todas las herramientas necesarias para este proyecto.

Por debajo de la visualización obviamente nosotros no vamos a guardar datos de ningún tipo, lo único que habría que hacer es obtener esta información del tráfico de alguna API abierta. Una búsqueda rápida me ha llevado al servicio rest de abajo de ArcGIS que parece que da información de Incidencias reportadas por la DGT. Habría que comprobar si la propia DGT tiene una API o podemos hacer webscrapping de los reportes de su web.

https://services1.arcgis.com/nCKYwcSONQTkPA4K/ArcGIS/rest/services/incidencias_DGT/FeatureServer/0

**Comment by ghost** [comment]
Perfecto. Muchas gracias por la explicación. 

También añadimos para el sistema de logs la librería `logging` de Python.

**Comment by rafasanjuan** [comment]
Cerramos hilo
